### ISSUE TITLE
System.Drawing.PointF structure

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/Arbor#11]
:question: What about inheriting `ArborGVT::ArborPoint` class from `System.Drawing.PointF`? Or you need C# `struct` and not its `class`? Or `Single` type doesn't have enough precision?

**Comment by Serg-Norseman** [comment]
PointF also is struct ))) except "float" we don't get anything out of it. If you look PointF methods and operators - useful is 2-3. Winning is almost there. And as for the "float" itself for a long time I think to try to translate all the calculations and look - may be enough

**Comment by Serg-Norseman** [comment]
Don't like to multiply entities. This inheritance will give nothing, no use

**Comment by ruslangaripov** [comment]
OK, I got it :smiling_imp: I thought there may be some overloaded operators in .NET for the `System.Drawing.PointF` class. And thus you can eliminate some methods from the `ArborGVT::ArborPoint`. But you said: "No! There's no profit there!" :raised_hands:
