### ISSUE TITLE
'ArborGVT::ArborSystem::updatePosition' implementation

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/Arbor#12]
## Given

The following loop exists in the `ArborGVT::ArborSystem::updatePosition` method:

``` csharp
foreach (ArborNode v in fNodes)
{
    v.Pt = v.Pt.add(v.v.mul(q));
    . . .
    ArborPoint y = v.Pt;
    if (y.exploded()) continue;
    . . .
}
```

This is definition of the `ArborGVT::ArborPoint::add` method:

``` csharp
public ArborPoint add(ArborPoint a)
{
    return new ArborPoint(this.x + a.x, this.y + a.y);
}
```

And the following code is definition of the `ArborGVT::ArborPoint::exploded` method:

``` csharp
public bool exploded()
{
    return (double.IsNaN(this.x) || double.IsNaN(this.y));
}
```
## The question

The first statement in the loop `v.Pt = v.Pt.add(v.v.mul(q))` increments `x` and `y` data members of `v.Pt` by some value. Had value of `x` or `y` be `NaN', I believe the code throws an exception. Does it?

Therefore **after that line** we can state that **`v.Pt.x` and `v.Pt.y` ain't NaN**. Otherwise exception generated by the `add` method would break execution.

And then we emit `if` statement:

``` csharp
    . . .
    ArborPoint y = v.Pt;
    if (y.exploded()) continue;
    . . .
```

that checks if `v.Pt.x` or `v.Pt.y` is NaN. But we already have proved that this cannot be! So my question is: "why do we check that again"?

**Comment by Serg-Norseman** [comment]
Good question )))))
Given that "exploded" is an expensive operation, good question... it line of course came from the original unchanged. We need to test and probably clean it.

**Comment by ruslangaripov** [comment]
A bad question! :bowtie:
`NaN` "plus" anything remains `NaN`. No exception is thrown. That's why "we check that again"!

**Comment by Serg-Norseman** [comment]
:(
