### ISSUE TITLE
Roll down of code and micro-optimizations

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/Arbor#17]
1. Roll down of function `ArborNode.applyForce()` increase speed of run `BarnesHutTree.applyForces()` by 30%.
2. If check arguments of `f.Enqueue(branch.Q[QNe]);` in `BarnesHutTree.applyForces()` before `Enqueue()` - it increase speed by 5-10%.
3. Roll down of function `ArborPoint.normalize()` yet increase speed by 3-5%.

Don't know if this makes sense.

**Comment by ruslangaripov** [comment]
What does "rolling down" stand for? Can you show new code for the `ArborNode.applyForce` method? I'm currently re-implement graph node, therefore it's interesting for me to see new version of the method.

Is the performance boost you've mentioned applied **only to Java code**?

When do you plan to push the update here? :smiling_imp:

**Comment by Serg-Norseman** [comment]
In this case, under "rolling down" I meant a replacement `=, add, div` to direct operators in function body:

```
internal void applyForce(ArborPoint a)
{
    //this.F = this.F.add(a.div(this.Mass));
    this.F.X += a.X / this.Mass;
    this.F.Y += a.Y / this.Mass;
}
```

It removes `ArborPoint.ctor`, other calls and overhead.
All this is more of a workout for the mind after a three-week hell of VBA-hardcore in OSIsoft ProcessBook :)
And not, all this items tested and profiled only for C#. Java label I put to the test and forgot to remove.

**Comment by Serg-Norseman** [comment]
For information: on 2000 iterations `updatePhysics()`, comes out to about 72 thousand calls `BarnesHutTree.applyForces()`, and 1.867 million calls `ArborNode.applyForce()`.

**Comment by ruslangaripov** [comment]
I got it! :smile: That's what temporary objects do in performance sensitive code!

> on 2000 iterations updatePhysics(), comes out to about 72 thousand calls BarnesHutTree.applyForces(), and 1.867 million calls ArborNode.applyForce()

"1.867 million calls" :open_mouth:

**Comment by Serg-Norseman** [comment]
To do rolldown or not to do, that is the question... :)
