### ISSUE TITLE
Data model

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/Arbor#8]
It is necessary to create a program data model for storing graph (its vertices and edges) meeting the following requirements:
- Graph may be mixed,
- Graph allows two or more edges that connect the same two vertices (_multigraph_) with enabled loops,
- Graph allows edges with only one end (_half-edges_).

[Graph (mathematics)](https://en.wikipedia.org/wiki/Graph_%28mathematics%29)

**Comment by Serg-Norseman** [comment]
I have the lite version of the classes set for the graph organization. Very light... when I prepared ArborGVT for the my project was the idea to integrate one with the other, but postponed. Decided that it is better to let ArborGVT have own ad-hoc implementation. In any case, when people need to work with graphs - they connected such powerful frameworks that the brain starts to crackle as wood in the cold! )))

**Comment by ruslangaripov** [comment]
:blush: But I need a simple "framework". In the meanwhile it should just be enough to render the graph :triangular_ruler:

**Comment by ruslangaripov** [comment]
:runner:
Because currently I don't have a clear mathematical model that was implemented in the C# sources (or in "original" JavaScript source code), I've decided to make "a copy" of the stuff crafted in the Csharp source code. So I won't make completed code re-engeneering targeting C++.
May be later, after I'll have finished with "copying" I'll rewrite the code.
